---
title: "Homework Part1"
author: "Lin Tian"
date: "6/26/2015"
output: html_document
---

Read data

```{r}
setwd("~/analyticEdge/week4/homework/homework_part1")
gerber <- read.csv("gerber.csv")
str(gerber)
mean(gerber$voting)
mean(subset(gerber, civicduty==1)$voting)
mean(subset(gerber, hawthorne==1)$voting)
mean(subset(gerber, self==1)$voting)
mean(subset(gerber, neighbors==1)$voting)
```

Build logistic regression model

```{r}
votingGLM <- glm(voting ~ civicduty+hawthorne+self+neighbors, data=gerber, family="binomial")
summary(votingGLM)
table(gerber$voting, predict(votingGLM, type="response")>0.3)
table(gerber$voting, predict(votingGLM, type="response")>0.5)
library(ROCR)
ROCRpred <- prediction(predict(votingGLM, type="response"), gerber$voting)
as.numeric(performance(ROCRpred, "auc")@y.values)
```

Build tree model

```{r}
library(rpart)
library(rpart.plot)
CARTmodel <- rpart(voting ~ civicduty + hawthorne + self + neighbors, data=gerber)
prp(CARTmodel)

CARTmodel2 <- rpart(voting ~ civicduty + hawthorne + self + neighbors, data=gerber, cp=0.0)
prp(CARTmodel2)

CARTmodel3 <- rpart(voting ~ civicduty + hawthorne + self + neighbors + sex, data=gerber, cp=0.0)
prp(CARTmodel3)

controlTree <- rpart(voting ~ control, data=gerber, cp=0.0)
prp(controlTree, digit=6)
controlSexTree <- rpart(voting ~ control + sex, data=gerber, cp=0.0)
prp(controlSexTree, digit=6)

controlSexLogReg <- glm(voting ~ control + sex, data=gerber, family=binomial)
summary(controlSexLogReg)
Possibilities <- data.frame(sex=c(0,0,1,1),control=c(0,1,0,1))
predict(controlSexLogReg, newdata=Possibilities, type="response")

LogModel2 <- glm(voting ~ sex + control + sex:control, data=gerber, family="binomial")
summary(LogModel2)
predict(LogModel2, newdata=Possibilities, type="response")
```

