---
title: "Homework Part1"
author: "Lin Tian"
date: "7/23/2015"
output: html_document
---

Set working directory and load dataset

```{r}
setwd("~/analyticEdge/week7/homework_part1")
library(ggplot2)
library(maps)
library(ggmap)
statesMap <- map_data("state")
ggplot(statesMap, aes(x = long, y = lat, group = group)) + geom_polygon(fill = "white", color = "black")
polling <- read.csv("PollingImputed.csv")
Train <- subset(polling, Year <= 2008)
Test <- subset(polling, Year == 2012)
```

Build logistic regression model

```{r}
mod2 <- glm(Republican~SurveyUSA+DiffCount, data=Train, family="binomial")
TestPrediction <- predict(mod2, newdata=Test, type="response")
TestPredictionBinary <- as.numeric(TestPrediction > 0.5)
predictionDataFrame <- data.frame(TestPrediction, TestPredictionBinary, Test$State)
mean(predictionDataFrame$TestPrediction)
```

Coloring the states by predictions

```{r}
predictionDataFrame$region <- tolower(predictionDataFrame$Test.State)
predictionMap <- merge(statesMap, predictionDataFrame, by = "region")
predictionMap <- predictionMap[order(predictionMap$order),]

ggplot(predictionMap, aes(x = long, y = lat, group = group, fill = TestPredictionBinary)) + geom_polygon(color = "black")

ggplot(predictionMap, aes(x = long, y = lat, group = group, fill = TestPredictionBinary))+ geom_polygon(color = "black") + scale_fill_gradient(low = "blue", high = "red", guide = "legend", breaks= c(0,1), labels = c("Democrat", "Republican"), name = "Prediction 2012")
```


