---
title: "homework part1"
author: "Lin Tian"
date: "6/3/2015"
output: html_document
---

Read data

```{r}
mvt <- read.csv("~/analyticEdge/week1/mvtWeek1.csv", as.is=TRUE)
dim(mvt)

## Maximum value of ID
max(mvt$ID)

## Minimum value of Beats
min(mvt$Beat)

## TRUE in the Arrest variable
sum(mvt$Arrest==TRUE)

## LocationDescription value of ALLEY
sum(mvt$LocationDescription=="ALLEY")
```

We can do the data conversion using R.

```{r}
DateConvert <- as.Date(strptime(mvt$Date, "%m/%d/%y %H:%M"))
median(DateConvert)

## extract the month and the day of the week
mvt$Month = months(DateConvert)
mvt$Weekday = weekdays(DateConvert)
## replace the old Date variable with DateConvert
mvt$Date = DateConvert

## fewest motor vehicle thefts month
which.min(table(mvt$Month))
## most motor vehicle thefts weekday
which.max(table(mvt$Weekday))
## month that has the largest number of motor vehicle thefts for which an arrest was made
which.max(table(mvt$Month, mvt$Arrest)[,"TRUE"])
```

We can use R to VISUALIZING CRIME TRENDS.

```{r}
hist(mvt$Year, breaks=100)
boxplot(mvt$Year ~ mvt$Arrest)
```

Proportion of motor vehicle thefts is arrestted

```{r}
## 2001
prop.table(table(mvt[mvt$Year==2001, "Arrest"]))
## 2007
prop.table(table(mvt[mvt$Year==2007, "Arrest"]))
## 2012
prop.table(table(mvt[mvt$Year==2012, "Arrest"]))
```

Popular Locations

```{r}
head(sort(table(mvt$LocationDescription), decreasing=TRUE))
PopularLocations <- names(head(sort(table(mvt$LocationDescription), decreasing=TRUE)))
PopularLocations <- PopularLocations[-3]
Top5 <- mvt[mvt$LocationDescription %in% PopularLocations, ]
Top5$LocationDescription = factor(Top5$LocationDescription)
dim(Top5)
prop.table(table(Top5$LocationDescription, Top5$Arrest), 1)
which.max(table(mvt[mvt$LocationDescription=="GAS STATION", "Weekday"]))
which.min(table(mvt[mvt$LocationDescription=="DRIVEWAY - RESIDENTIAL", "Weekday"]))
```


