---
title: "Homework Part1"
author: "Lin Tian"
date: "7/3/2015"
output: html_document
---

Read data

```{r}
setwd("~/analyticEdge/week5/homework/homework_part1")
wiki <- read.csv("wiki.csv", as.is = TRUE)
sum(wiki$Vandal==1)
```

Create corpusAdded

```{r}
library(tm)
corpusAdded <- Corpus(VectorSource(wiki$Added))
corpusAdded <- tm_map(corpusAdded, PlainTextDocument)
corpusAdded <- tm_map(corpusAdded, removeWords, stopwords("english"))
corpusAdded <- tm_map(corpusAdded, stemDocument)
dtmAdded <- DocumentTermMatrix(corpusAdded)
sparseAdded <- removeSparseTerms(dtmAdded, 0.997)
wordsAdded <- as.data.frame(as.matrix(sparseAdded))
colnames(wordsAdded) = paste("A", colnames(wordsAdded))
```

Create corpusRemoved

```{r}
corpusRemoved <- Corpus(VectorSource(wiki$Removed))
corpusRemoved <- tm_map(corpusRemoved, PlainTextDocument)
corpusRemoved <- tm_map(corpusRemoved, removeWords, stopwords("english"))
corpusRemoved <- tm_map(corpusRemoved, stemDocument)
dtmRemoved <- DocumentTermMatrix(corpusRemoved)
sparseRemoved <- removeSparseTerms(dtmRemoved, 0.997)
wordsRemoved <- as.data.frame(as.matrix(sparseRemoved))
colnames(wordsRemoved) = paste("R", colnames(wordsRemoved))
```

Combine Added and Removed

```{r}
wikiWords <- cbind(wordsAdded, wordsRemoved)
wikiWords$Vandal <- wiki$Vandal
library(caTools)
set.seed(123)
spl <- sample.split(wiki$Vandal, SplitRatio = 0.7)
train <- subset(wikiWords, spl==TRUE)
test <- subset(wikiWords, spl==FALSE)
```

CART model

```{r}
library(rpart.plot)
wikiCART <- rpart(Vandal ~ ., data=train, method="class")
prp(wikiCART)
predTest <- predict(wikiCART, newdata=test, type="class")
table(test$Vandal, predTest)
```

Improve the model -- Step1

```{r}
wikiWords2 <- wikiWords
wikiWords2$HTTP <- ifelse(grepl("http",wiki$Added,fixed=TRUE), 1, 0)
wikiTrain2 <- subset(wikiWords2, spl==TRUE)
wikiTest2 <- subset(wikiWords2, spl==FALSE)
wikiCART2 <- rpart(Vandal ~ ., data=wikiTrain2, method="class")
prp(wikiCART2)
predTest2 <- predict(wikiCART2, newdata=wikiTest2, type="class")
table(test$Vandal, predTest2)
```

Improve the model -- Step2

```{r}
wikiWords2$NumWordsAdded <- rowSums(as.matrix(dtmAdded))
wikiWords2$NumWordsRemoved <- rowSums(as.matrix(dtmRemoved))
wikiTrain2 <- subset(wikiWords2, spl==TRUE)
wikiTest2 <- subset(wikiWords2, spl==FALSE)
wikiCART2 <- rpart(Vandal ~ ., data=wikiTrain2, method="class")
prp(wikiCART2)
predTest2 <- predict(wikiCART2, newdata=wikiTest2, type="class")
table(test$Vandal, predTest2)
```

Improve the model -- Step3

```{r}
wikiWords3 <- wikiWords2
wikiWords3$Minor <- wiki$Minor
wikiWords3$Loggedin <- wiki$Loggedin
wikiTrain3 <- subset(wikiWords3, spl==TRUE)
wikiTest3 <- subset(wikiWords3, spl==FALSE)
wikiCART3 <- rpart(Vandal ~ ., data=wikiTrain3, method="class")
prp(wikiCART3)
predTest3 <- predict(wikiCART3, newdata=wikiTest3, type="class")
table(test$Vandal, predTest3)
```


