---
title: "Homework Part3"
author: "Lin Tian"
date: "7/9/2015"
output: html_document
---

Read dataset

```{r}
setwd("~/analyticEdge/week6/homework/homework3")
stocks <- read.csv("StocksCluster.csv")
dim(stocks)
head(unique(sort(cor(stocks[, 1:11]), decreasing=TRUE)))
which.max(colMeans(stocks[, 1:11]))
which.min(colMeans(stocks[, 1:11]))
```

Logistic Regression Model

```{r}
library(caTools)
set.seed(144)
spl <- sample.split(stocks$PositiveDec, SplitRatio = 0.7)
stocksTrain <- subset(stocks, spl == TRUE)
stocksTest <- subset(stocks, spl == FALSE)
StocksModel <- glm(PositiveDec ~ ., data=stocksTrain, family="binomial")
table(stocksTrain$PositiveDec, predict(StocksModel, type="response")>0.5)
table(stocksTest$PositiveDec, predict(StocksModel, newdata=stocksTest, type="response")>0.5)
```

Clustering

```{r}
limitedTrain <- stocksTrain
limitedTrain$PositiveDec <- NULL
limitedTest <- stocksTest
limitedTest$PositiveDec <- NULL
# Preprocess the dataset
library(caret)
preproc <- preProcess(limitedTrain)
normTrain <- predict(preproc, limitedTrain)
normTest <- predict(preproc, limitedTest)
colMeans(normTrain)
colMeans(normTest)
```

k-means clustering

```{r}
set.seed(144)
km <- kmeans(normTrain, centers = 3)
km$size

library(flexclust)
km.kcca <- as.kcca(km, normTrain)
clusterTrain <- predict(km.kcca)
clusterTest <- predict(km.kcca, newdata=normTest)
sum(clusterTest==2)
```

Clustering specific predictions

```{r}
stocksTrain1 <- stocksTrain[clusterTrain==1, ]
stocksTrain2 <- stocksTrain[clusterTrain==2, ]
stocksTrain3 <- stocksTrain[clusterTrain==3, ]
stocksTest1 <- stocksTest[clusterTest==1, ]
stocksTest2 <- stocksTest[clusterTest==2, ]
stocksTest3 <- stocksTest[clusterTest==3, ]

StocksModel1 <- glm(PositiveDec ~ ., data=stocksTrain1, family="binomial")
StocksModel2 <- glm(PositiveDec ~ ., data=stocksTrain2, family="binomial")
StocksModel3 <- glm(PositiveDec ~ ., data=stocksTrain3, family="binomial")
cbind(summary(StocksModel1)$coef[, 1], summary(StocksModel1)$coef[, 1], summary(StocksModel1)$coef[, 1])

PredictTest1 <- predict(StocksModel1, newdata=stocksTest1, type="response")
table(stocksTest1$PositiveDec, PredictTest1>0.5)
PredictTest2 <- predict(StocksModel2, newdata=stocksTest2, type="response")
table(stocksTest2$PositiveDec, PredictTest2>0.5)
PredictTest3 <- predict(StocksModel3, newdata=stocksTest3, type="response")
table(stocksTest3$PositiveDec, PredictTest3>0.5)

AllPredictions <- c(PredictTest1, PredictTest2, PredictTest3)
AllOutcomes <- c(stocksTest1$PositiveDec, stocksTest2$PositiveDec, stocksTest3$PositiveDec)
table(AllOutcomes, AllPredictions>0.5)
```

